feat: add color presentations
web-lsp/csslsrs pull request #3
Opened 2024-10-31 23:36 UTC by Princesseuh

Still missing entries for more exotic color formats (lab, etc)

2024-11-02 12:49 UTC, goulvenclech requested changes
LGTM but OÙ EST LA DOOOOOOC ???

2024-11-16 16:05 UTC, Princesseuh commented on src/features/color_parser.rs
> +use palette::named;
I'll contribute a fair amount of this file directly to palette eventually, so hopefully we won't keep it around too much.

2024-11-16 16:09 UTC, Princesseuh commented on Cargo.toml
> +palette = "0.7.6"
I choose palette because it makes it fairly easy and performant to convert between different formats and is well maintained (and generally striving to be CSS compliant). 

`csscolorparser` was more directly useful, but it parsed certain values wrong and didn't support some of the things we need / we'll need in the future.

2024-11-16 17:38 UTC, goulvenclech approved these changes

2024-11-16 17:38 UTC, merged